ALTER TABLE PERFORM_LOG DROP PRIMARY KEY;

DROP INDEX PK_PERFORM_LOG;

/* 성능측정 */
DROP TABLE PERFORM_LOG 
	CASCADE CONSTRAINTS;

/* 성능측정 */
CREATE TABLE PERFORM_LOG (
	SEQ NUMBER NOT NULL, 
	PAC_METHOD VARCHAR2(200 BYTE) NOT NULL, 
	PARAM VARCHAR2(4000 CHAR), 
	RUN_TIME NUMBER(7,3) NOT NULL, 
	REG_DT DATE DEFAULT SYSDATE 
);

COMMENT ON TABLE PERFORM_LOG IS '성능측정';

COMMENT ON COLUMN PERFORM_LOG.SEQ IS '순번';

COMMENT ON COLUMN PERFORM_LOG.PAC_METHOD IS '패키지_메서드';

COMMENT ON COLUMN PERFORM_LOG.PARAM IS '인자';

COMMENT ON COLUMN PERFORM_LOG.RUN_TIME IS '수생시간';

COMMENT ON COLUMN PERFORM_LOG.REG_DT IS '등록일';

CREATE UNIQUE INDEX PK_PERFORM_LOG
	ON PERFORM_LOG (
		SEQ ASC
	);

ALTER TABLE PERFORM_LOG
	ADD
		CONSTRAINT PK_PERFORM_LOG
		PRIMARY KEY (
			SEQ
		);